Update composer.json to use compatible monolog version
graycoreio/magento2-stdlogging pull request #4
Opened 2020-10-03 07:16 UTC by marciomaciel

Changed monolog version from "1.17" to "^1.16" to match version used in Magento 2.4

2020-10-03 13:50 UTC, damienwebdev requested changes
@marciomaciel can you update the `composer.lock` as well?

2020-10-03 13:51 UTC, damienwebdev commented
/azp run

2020-10-23 13:52 UTC, benjick commented
Will this be merged?

Getting this error while installing:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - Can only install one of: monolog/monolog[1.25.5, 1.17.0].
    - Can only install one of: monolog/monolog[1.17.0, 1.25.5].
    - Can only install one of: monolog/monolog[1.17.0, 1.25.5].
    - graycore/magento2-stdlogging v1.1.0 requires monolog/monolog 1.17 -> satisfiable by monolog/monolog[1.17.0].
    - Installation request for graycore/magento2-stdlogging ^1.1 -> satisfiable by graycore/magento2-stdlogging[v1.1.0].
    - Installation request for monolog/monolog (locked at 1.25.5) -> satisfiable by monolog/monolog[1.25.5].
```

and I guess this PR will fix that

2020-10-23 14:59 UTC, damienwebdev commented
The code is fine, I just don't have the time to bump the lockfile (seems ridiculous I know). @benjick if you wouldn't mind submitting a PR to dump the deps and the lockfile, I'd merge it.

2020-10-23 17:10 UTC, damienwebdev commented
Closing in favor of https://github.com/graycoreio/magento2-stdlogging/commit/3380ca7a3c971b7f857b77821a582459f9055c34

2020-10-23 17:10 UTC, closed without merging

2020-10-23 17:10 UTC, damienwebdev commented
@benjick this is merged and released as v1.1.1.